# Generated by Django 4.0.3 on 2022-06-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('rank', models.TextField()),
                ('dodin', models.TextField()),
                ('social_security_number', models.TextField()),
                ('dafsc', models.TextField()),
                ('email', models.TextField()),
                ('dsn_phone', models.TextField()),
                ('commercial_phone', models.TextField()),
                ('organization', models.TextField()),
                ('unit_mailing_address', models.TextField()),
                ('duty_title', models.TextField()),
                ('designation_of_person_military', models.BooleanField()),
                ('designation_of_person_civilian', models.BooleanField()),
                ('designation_of_person_contractor', models.BooleanField()),
                ('citizenship_us', models.BooleanField()),
                ('citizenship_fn', models.BooleanField()),
                ('citizenship_other', models.BooleanField()),
                ('ia_training_complete', models.BooleanField()),
                ('ia_training_date', models.TextField()),
            ],
        ),
    ]
